resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_siddharth-dhawan
    name: siddharth-dhawan/app-service-web-html-get-started
    trigger:
      branches:
        include:
        - main
        - release


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: CI

    steps:
    - checkout: MyGitHubRepo
    - task: CopyFiles@2
      inputs:
        SourceFolder: './'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
