trigger:
- development

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: CI

    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: './'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
