resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: wqekeux4izbgqvdsuqsg6dteyayxxymum2xehbedxfoyr4hifpra
    name: siddharth-dhawan/app-service-web-html-get-started



# trigger:
# - development

pool:
  vmImage: ubuntu-latest

- checkout: MyGitHubRepo

stages:
- stage: Build
  jobs:
  - job: CI

    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: './'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
